services:
  mortgage:
    image: mortgage:1.0.0
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8082
    # ports:
    #   - 8082:8082
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mortgage.rule=Host(`mortgage.reftch.com`)
      - traefik.http.services.mortgage.loadbalancer.server.port=8082

networks:
  traefik_proxy:
    external: true
